### ISSUE TITLE
Environment.js file is not updated

### ISSUE THREAD

**Issue by netcurate** [j-mcnally/ember-cli-chrome#3]
Hi,

Strange issue and not sure if it related to ember-cli-chrome. So, I could successfully deploy the chrome extension on local machine. 

I am printing my environment.js "config" just to see the values, I notice that these values are not updated based on my code base. If I run the same code in normal browser instance, it works fine.

I also notice that these environment.js contents are quite old (I had deployed the extension few days back) and seems like these values are coming from there - somehow!!! I uninstalled chrome and installed it back - no luck.

What could be happening?

**Comment by j-mcnally** [comment]
New approach is to just use the inline meta tag. The way the new ember-clis handle environment is more compatible with chrome extensions.
