### ISSUE TITLE
Not a properly formatted package

### ISSUE THREAD

**Issue by majochoc** [j-mcnally/ember-cli-chrome#4]
ember-cli 0.2.1 complains that ember-cli-chrome doesn't have an index.js file, and therefore is not a properly formatted add-on. Can this be ignored since ember-chrome.js is being included, and it does the heavy lifting?

**Comment by j-mcnally** [comment]
the extension will be updated for the latest ember-cli shortly. we used a lot of hacks because the type of injection and changes we are doing were not on the happy path back when we started with 0.0.39, now that official stable apis exist, things will work better moving forward.

**Comment by EmergentBehavior** [comment]
@j-mcnally Any updates on this?

**Comment by j-mcnally** [comment]
This is fixed, switched to just using an index.js as the entry point.
