### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by EmergentBehavior** [j-mcnally/ember-cli-chrome#6]
Am using it myself -- had to fork to make a required compatibility change for latest ember-cli.

**Comment by pete-the-pete** [comment]
I am still using it, what change did you need to make?

**Comment by edborden** [comment]
@EmergentBehavior can you share your fork or create a pull request on this repo?

**Comment by EmergentBehavior** [comment]
If @j-mcnally is still actively working on it can submit a PR -- here's my fork (using it for a new company): https://github.com/WeCrewt/ember-cli-chrome

Main changes are adding a `main` entry point (similar to other forks) and moving to `broccoli-funnel` since `broccoli-static-compiler` is apparently deprecated. May add other changes as I work on this,

**Comment by j-mcnally** [comment]
so sorry guys for being lame at this. I just havent developed a chrome extension in a while, and as a result I hadn't taken the time to update this plugin. The good news is I have a new pet project so it will get some love. Im going to pull in the great work that @EmergentBehavior and WeCrewt did and make sure everything is stable. That will happen today.

Being the solo dev on this and having a lot of other paid work has gotten in the way of this progressing and for that I am sorry.

Again sorry for the delay.

**Comment by j-mcnally** [comment]
New version 0.0.6 pushed with latest Ember-cli support. 

Refactors the whole code base, uses new best practices and support for 3rd party trees.

Forcefully sets locationType to hash.

**Comment by EmergentBehavior** [comment]
Cool thanks @j-mcnally! Though I think you need to bump the `ember-cli` version here too: https://github.com/j-mcnally/ember-cli-chrome/blob/master/package.json#L16

**Comment by j-mcnally** [comment]
Done!
