### ISSUE TITLE
TypeError: Cannot set property 'enabled' of undefined

### ISSUE THREAD

**Issue by rafaltrojanowski** [j-mcnally/ember-cli-chrome#9]
Does somebody have this error?

```
TypeError: Cannot set property 'enabled' of undefined
  at EmberCLIChrome.included (/.../.../node_modules/ember-cli-chrome/lib/chrome-app.js:118:35)
```

**Comment by j-mcnally** [comment]
what version of ember-cli are you using?

**Comment by rafaltrojanowski** [comment]
I tested with 0.2.7 and 1.13.1

**Comment by kyleshevlin** [comment]
At the risk of sounding dumb, but I'm guessing the fix is merged but not released. Just installed ember-cli-chrome 0.0.7 tonight and had to add in the `add.options.fingerprint..` code that @robbiewain added to get the server running. Is this accurate?

**Comment by j-mcnally** [comment]
Yeah i need to cut a new release.

On Wed, Aug 5, 2015 at 12:15 AM, Kyle Shevlin <notifications@github.com>
wrote:

> At the risk of sounding dumb, but I'm guessing the fix is merged but not
> released. Just installed ember-cli-chrome 0.0.7 tonight and had to add in
> the add.options.fingerprint.. code that @robbiewain
> <https://github.com/robbiewain> added to get the server running. Is this
> accurate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j-mcnally/ember-cli-chrome/issues/9#issuecomment-127857597>
> .
>



-- 

<http://www.kohactive.com>
Justin McNally
Technology Director / Principal
p: 312.273.3074 <+13122733074> | e: justin@kohactive.com | skype:
justinmcnally211 <http://is.gd/UuXAGG>
  <https://github.com/j-mcnally>  <https://twitter.com/j_mcnally>
<https://www.linkedin.com/profile/view?id=143776726>

**Comment by rafaltrojanowski** [comment]
Thanks @robbiewain @j-mcnally
